services:
  postgres:
    image: postgres:17-alpine
    container_name: sadikov-kamal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sadikov_kamal_admin
      POSTGRES_PASSWORD: dev_password_change_me
      POSTGRES_DB: sadikov_kamal
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
