-- Apply the "stable code per entity" philosophy to problems.
--
-- Differences from topics/sources/age_categories:
--   • code is a plain integer (no padding, no prefix). Sorts naturally
--     numerically — 1, 2, …, 10, 11, …, 100. The previous tables used
--     T###### / S###### / A###### because their codes were embedded in
--     conversation ("Mavzu T000042 ni och"); problems are referenced
--     so often that the prefix would be noise.
--   • Sequence-managed via GENERATED BY DEFAULT AS IDENTITY so new
--     rows auto-pick the next number without race conditions. Manual
--     overrides are still possible (e.g. data imports that want to
--     preserve historical IDs).
--
-- Also drops fields that are now out of scope:
--   • solution_md — solutions aren't tracked in this app
--   • answer     — not part of the content model
--   • year       — sources are nested granularly enough that year goes
--                  into the source itself ("IMO 2024")
--
-- problem_number stays (text field for external/contextual numbering
-- like "Day 2 / 3" or "P6").

-- 1. Drop dependent indexes / constraints first.
DROP INDEX IF EXISTS "problems_source_year_idx";
DROP INDEX IF EXISTS "problems_source_year_number_unique";
ALTER TABLE "problems" DROP CONSTRAINT IF EXISTS "problems_year_check";

-- 2. Drop columns that are gone.
ALTER TABLE "problems" DROP COLUMN IF EXISTS "solution_md";
ALTER TABLE "problems" DROP COLUMN IF EXISTS "answer";
ALTER TABLE "problems" DROP COLUMN IF EXISTS "year";

-- 3. Add code (nullable first so existing rows survive the ADD).
ALTER TABLE "problems" ADD COLUMN "code" integer;

-- 4. Backfill: sequential 1.. in created_at order. Reproducible across
-- environments because created_at is a real timestamp.
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) AS seq
  FROM "problems"
)
UPDATE "problems" p
SET "code" = o.seq
FROM ordered o
WHERE p.id = o.id;

-- 5. Enforce NOT NULL + UNIQUE now that every row has a code.
ALTER TABLE "problems" ALTER COLUMN "code" SET NOT NULL;
ALTER TABLE "problems" ADD CONSTRAINT "problems_code_unique" UNIQUE ("code");

-- 6. Attach an IDENTITY sequence starting one past the current max.
-- BY DEFAULT (not ALWAYS) so a future restore script that wants to
-- preserve specific codes can override; normal app inserts let it
-- generate.
DO $$
DECLARE
  next_code integer;
BEGIN
  SELECT COALESCE(MAX(code), 0) + 1 INTO next_code FROM "problems";
  EXECUTE format(
    'ALTER TABLE "problems" ALTER COLUMN "code" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    next_code
  );
END $$;

CREATE INDEX IF NOT EXISTS "problems_code_idx" ON "problems" ("code");

-- 7. New cheaper source index (no year now).
CREATE INDEX IF NOT EXISTS "problems_source_idx" ON "problems" ("source_id");

-- 8. Dedupe constraint without year. Same source can't have two rows
-- with the same problem_number (when set). NULL problem_numbers are
-- allowed in unlimited quantity.
CREATE UNIQUE INDEX IF NOT EXISTS "problems_source_number_unique"
  ON "problems" ("source_id", "problem_number")
  WHERE "problem_number" IS NOT NULL;
